name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, json, pdo, pdo_mysql
          coverage: xdebug  # Add this line
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --no-check-all --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: composer test

  test-windows:
    name: PHP ${{ matrix.php }} on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, json
          coverage: xdebug  # Add this for Windows too

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: composer test
